USE onlinestore_db;

INSERT INTO categories (categoryname) VALUES ('Sofas');
INSERT INTO categories (categoryname) VALUES ('Chairs');
INSERT INTO categories (categoryname) VALUES ('Tables');
INSERT INTO categories (categoryname) VALUES ('Living Room Sets');

INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Flared ArmLoveseat','Rainy weekend afternoons are meant for naps, and some of the best naps happen on a couch in front of the TV, fireplace, or even a window with a view of the rain. This loveseat, for example, has a frame constructed of solid and manufactured wood, upholstered with 100% polyester, and filled with foam. It features flared arms, a tufted back, and nailhead trim. Needing light assembly, you will be lounging on this sectional in no time.','/assets/img/Sofas/Flared+Arm+Loveseat.jpg',609.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Bel Air Sofa','Anchor your living room in sophisticated style and impeccable comfort with a single addition. Perfectly balancing wood accents with fabric upholstery, this impressive sofa offers your home a charming mid-century modern upgrade. This piece offers a beautiful button tufted design that is finished with diamond stitching in the backrest and waffle stitching in the seating. Completed with iconic splayed legs with gold tips and lovely rolled accent pillows, this refined sofa will make any interior space into a stunning masterpiece.','/assets/img/Sofas/Bel-Air+Sofa.jpg',589.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Benitez Full 76" Convertible Sofa','With its streamlined silhouette and simple, squared cushions, this mid-century modern-inspired sofa lends inviting appeal to your seating ensemble. Featuring a frame made from a practical mixture of solid and manufactured wood in a rich brown finish, this design sports button-tufted faux leather upholstery, innerspring coil support, slick track arms, and five round tapered legs. When you’re finished watching your favourite shows and it’s time to retire, just fold the back down and this charismatic design effortlessly converts into a bed that sleeps two.','/assets/img/Sofas/Benitez+Full+Convertible+Sofa.jpg',509.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Bjorn 59" Rolled Arm Settee','This settee is the perfect pick for a small-scale seating ensemble or a bedroom accent. Made from solid maple wood, it offers a traditional appearance with rolled arms and turned legs finished in walnut. Foam padding and web suspension add comfort to the seat, while 100% polyester upholstery ties it all together with button tufts and a neutral solid hue.','/assets/img/Sofas/Bjorn+Rolled+Arm+Settee.jpg',479.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Corwin Convertible Sleeper','The Corwin pairs classic and modern in streamlined style. Featuring high density foam and sleek chrome metal legs and self-pipping tufting, this sofa effortlessly converts quickly to a bed. Surprise your guests and re-define comfort with the Corwin.','/assets/img/Sofas/Corwin+Convertible+Sleeper.jpg',249.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Darren Tufted Loveseat','Perfect for rounding out a seating ensemble or a space-conscious area a lounge-worthy touch, loveseats like this are a great option for all the comfort of a sofa without dominating your home square footage. Crafted from a solid wood frame wrapped in 100% linen, this piece features a clean-lined silhouette perfect for a contemporary look. Tapered wood legs with a dark espresso finish and button tufting round this piece out with a touch of mid-century style.','/assets/img/Sofas/Darren+Tufted+Loveseat.jpg',499.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Koger Velvet Flared Arm Sofa','Lean back and lounge in luxurious style on this stunning sofa. This sofa features plush velvet upholstery that is both classy and sumptuous against your skin a single seat cushion and rounded arms that curve into a low rounded back creating a perfect modern piece for your home. Gold stainless steel legs support this sofa and provide a stunning contrast to the sofa plush.','/assets/img/Sofas/Koger+Velvet+Flared+Arm+Sofa.jpg',1369.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Marcelo 40.5" Armless Settee','A spacious work space chair, a seat at the foot of the bed; you name it, this settee brings style and function to any room of the house. Upholstered in 100% polyester, this piece sports a bold damask pattern for a touch of bohemian appeal, while solid wood legs, awash in dark espresso, complete the look. Sporting a clean, arm less silhouette, this settee pulls up flush to tables and coordinates effortlessly with existing furniture – seating two and holding up to 500 lbs. wherever it lives.','/assets/img/Sofas/Marcelo+Armless+Settee.jpg',263.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Minter 89" Pillow Top Arm Sofa Bed','This transitional sleeper sofa features very plush pillow top arms for additional comfort while sitting, reclining or sleeping. A single touch transforms this full-size sleeper sofa into a bed. Make room for an unexpected guest or create a modern bedroom with this updated convertible futon that is so easy to assemble. The sofa sleeper is a very versatile piece of furniture that has a three-position click style hinge which allows you to sit, recline or sleep 2 comfortably. Polyester fibre, foam and innerspring seat and back cushion. No annoying bar in the back for added sleeping comfort.','/assets/img/Sofas/Minter+Pillow+Top+Arm+Sofa+Bed.jpg',599.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Pepperell 72" Square Arm Sofa Bed','Going from day to night in a snap, this sleeper sofa is a perfect pick for any space. Crafted from solid and manufactured wood, this streamlined design is wrapped in linen upholstery for a touch of texture, while button tufts give it a dash of classic character. Got an unexpected guest? Simply transform this item into a sleeper, and voila – a space for them to rest their head. It measures 34'' H x 81'' W x 39'' D overall.','/assets/img/Sofas/Pepperell+Square+Arm+Sofa+Bed.jpg',669.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Quinones Chesterfield 54 inches Rolled Arms Loveseat','Modelled after the classic British Chesterfield sofa, this loveseat brings a traditional element to your den, library, or home office. Upholstered with inviting fabric and filled with foam, its tight back and rolled arms feature deep button tufting as a nod to the iconic piece of furniture. It sits atop four stacked bun feet – simply screw them in for easy assembly, then curl up with a good book or cup of tea!','/assets/img/Sofas/Quinones+Chesterfield+54+inches+Rolled+Arms+Loveseat.jpg',739.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Stevie Tufted Back Convertible Sofa','The Novogratz Stevie Futon is the perfect modern sofa bed for those who want practicality without compromising on style. Designed with rounded edges on the armrests, back and seat, the Stevie also features some button tufted detailing in the soft velvet upholstery. This convertible sofa bed is constructed with a strong plywood frame to ensure that it will last you through university and make it into your first apartment. To make this futon even better, the Novogratz Stevie Futon is built with a multi-functional design that allows you to recline the backrest between three position with an easy push or pull. This means you get to choose if you want your futon to be in a sitting position for long hours of studying, in a lounging position for a weekend long movie marathon, or in a sleeping position for hosting your friends overnight during the weekend. Available in multiple trendy colours, the Novogratz Stevie Futon is the ideal option to add a pop of style to your living room, home office or guest bedroom.','/assets/img/Sofas/Stevie+Tufted+Back+Convertible+Sofa.jpg',469.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Kalea 52" Armless Settee','Inspired by the curvaceous, fun designs of the mid-century modern aesthetic, this settee is a perfect pick for completing a retro living space or adding a dash of mod appeal to an ensemble. Founded atop tapered legs, its birch wood frame is wrapped in velvet upholstery and accented by button tufting, while hand-tied springs pair with foam fill to encourage a comfortable seat, whether you’re kicking back with the latest book club read or simply watching the nightly news.','/assets/img/Sofas/Kalea+Armless+Settee.jpg',1129.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Jezebel 43.5" Recessed Arm Settee','Treat your interior space to a unique elemental twist that comes from charming French influences. With tasteful designs such as curved tapered legs and a button-tufted backrest, this settee is ideal for any setting. Not only does this provide a luxurious look to your décor but this also offers exceptional comfort with its diamond stitching and plush seating. Ideal for small spaces, this piece will easily become a perfect statement piece in your home or apartment for years to come.','/assets/img/Sofas/Jezebel+Recessed+Arm+Settee.jpg',599.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Koger Velvet Chesterfield 65" Round Arm Loveseat','Lean back and lounge in luxurious style on this stunning loveseat. This glam loveseat features plush velvet upholstery that is both classy and sumptuous against your skin, a single seat cushion and rounded arms that curve into a low, rounded back, creating a perfect, modern piece for your home. Gold stainless steel legs support this loveseat and provide a stunning contrast to the loveseats plush.','/assets/img/Sofas/Koger+Velvet+Chesterfield+Round+Arm+Loveseat.jpg',1089.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Roderick 78.25" Square Arm Sofa','Sink back into sweet relief after a long day at work in the comfort of our pillow-backed sofa. This three-seater sofa offers your interior space eye-catching aesthetics with its tonal piping and delightfully sloped arms, making this piece a perfect contemporary addition for any room. Finished with sleek tapered legs, this piece not only anchors your decor in refined elegance but it also provides incredible relaxation for all. From cozy movie night gatherings to casual conversations, our sofa will have you anchored in style.','/assets/img/Sofas/Roderick+Square+Arm+Sofa.jpg',599.99);

INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Brittnie Barrel Chair','This chair combines the traditional and classic style, which are perfect for your restaurant, living room, coffee house, patio, bedroom, or any other decor theme, an ergonomic oversized chair, designed for comfort, durability, and impeccable style.','/assets/img/Chairs/Brittnie+Barrel+Chair.jpg',249.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Bulter Armchair','This Armchair showcases a scrolling botanical motif for a pop of pattern. This low-profile piece is crafted with a solid birch frame, foam fill, and quality upholstery to offer a firm feel as you sit back and relax.','/assets/img/Chairs/Bulter+Armchair.jpg',206.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Didonato Velvet Tufted Upholstered Armchair','This elegant accent chair updates the classic armchair with dramatic curves and embracing comfort. With lustrous highlights and shadows, the velvet upholstery and tufted button.','/assets/img/Chairs/Didonato+Velvet+Tufted+Upholstered+Armchair.jpg',409.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Garren 22.4" Club Chair','Showcasing simplified design and a clean-cut silhouette, this charismatic armchair is a mid-century modern style statement piece perfect for your living room or study. Made with a kiln-dried solid hardwood frame, this dapper design sports plush polyester blend upholstery with high-density foam fill and pocket coil suspension, sleek track arms, two bolster pillow cushions, and round, tapered, rubberwood legs.','/assets/img/Chairs/Garren+Club+Chair.jpg',329.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Halesworth Armchair','A flared, button tufted back and loose seat nestled in this classic frame make this chair a charming addition to your living space. Wrapped roll arms and box seat piping back make the styling complete; every detail thought of','/assets/img/Chairs/Halesworth+Armchair.jpg',299.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Holeman Velvet Slipper Chair','Fun and funky, this chair will add a vibrant accent to your home’s modern décor. This retro-inspired accent chair is sure to draw attention. Dark brown finished wood legs, button accent, and contoured shape lend to the unique styling of the chair.','/assets/img/Chairs/Holeman+Velvet+Slipper+Chair.jpg',179.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Jayde Armchair','Rounding out your decor while providing sensible seating arrangements in small spaces, side chairs offer style and versatility to any interior design. Take this one for example: crafted from solid wood, it features four legs (two turned and two flared) awash in a neutral espresso finish, while the seat and barrel back boast foam-filled linen upholstery in a solid hue. Plus, it sports a button-tufted accents and nailhead trim for eye-catching appeal.','/assets/img/Chairs/Jayde+Armchair.jpg',409.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Kayla Lounge Chair','Whether pulled up to your dining room ensemble or accenting your bedroom or living room look, this side chair brings contemporary style with a touch of rustic appeal to any space. Crafted from solid wood, the frame features two curved arms and boasts a natural wood grain brown finish for a dash of classic character. Plus, it showcases 100% polyester upholstery filled with foam for added comfort.','/assets/img/Chairs/Kayla+Lounge+Chair.jpg',329.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Nisha 23" Wingback Arm Chair','A classic silhouette gets a contemporary upgrade in this curated chair. Founded on a solid birch wood frame, this dapper design strikes an updated wingback silhouette with curvy track arms and tapered square legs in a deep espresso finish. Sporting a fashionable solid hue, brushed polyester upholstery envelops the whole chair, accented by corded edges for a tailored touch, while web suspension, pocket springs support, and synthetic fibre-wrapped foam cushion cores provide comfort and support.','/assets/img/Chairs/Nisha+Wingback+Arm+Chair.jpg',409.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Rotterdam 22.5" Armchair','Accent a traditional dining room set or provide extra seating in the living room with this armchair. Crafted from a solid and manufactured wood frame, it showcases arms that start with a curve and end in a square shape, and a straight back for an updated yet traditional design. Upholstered in a polyester blend, its seat and back feature a foam fill for an inviting look. Nailhead trim completes the look.','/assets/img/Chairs/Rotterdam+Armchair.jpg',405.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Caryn 22.5" Wingback Chair','A traditional silhouette gets a contemporary refresh with this wingback chair, an updated classic. Founded atop four tapered legs in a dark espresso finish, this piece is crafted with a pine, poplar, and plywood frame that supports up to 300 lbs. Foam and polyester fibre fill provide cushioning as you kick back and unwind, while fabric upholstery envelops this design to make it even more inviting. Assembly is required. A toss pillow is included.','/assets/img/Caryn+Wingback+Chair.jpg',469.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Hubbard Wingback Chair','This Hubbard Wingback Chair with gold legs is the epitome of glam design. This chair features a super luxurious velvet fabric, that feels good to the touch. Button tufting on the back and seat bring the glam, while the gold medal tapered legs bring the modern design.','/assets/img/Hubbard+Wingback+Chair.jpg',579.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Darren 21" Armchair','Blending traditional design with a touch of contemporary flair, this armchair is a perfect finishing touch to your classic entertainment space. Defined by its streamlined wood frame and square arms, this chair is upholstered in linen fabric to bring a textured touch to your ensemble, while its solid hue blends into monochromatic and vibrant palettes alike. Button-tufted detailing on the seat, cushion, and back add a final note of visual interest.','/assets/img/Darren+Armchair.jpg',343.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Wydmire 25.5" Armchair','When it comes to adding accent seating, an armchair is a great option for adding both a cozy spot to recline and a touch of gravitas to any room. This piece, crafted from manufactured wood with in a Mission style, features microfiber upholstery and a foam-filled seat, so you can recline in comfort. Perfect for adding a touch of traditional style inspired by the American West.','/assets/img/Wydmire+Armchair.jpg',509.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'London Wingback Chair','The perfect spot to sip your morning coffee or flip through the pages of a bestseller, this armchair invites you to kick back and enjoy the comforts of home. A wingback design and rolled arms make this piece an instant classic, while striped polyester blend fabric completes the look with a textured feel and fresh, clean appeal. This chair has a medium seating firmness.','/assets/img/London+Wingback+Chair.jpg',369.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Thelma Velvet 22" Chesterfield Chair','Live a life of luxury with this chair that gives you everything from incredible textures to exquisite style. It is the ideal addition to any living room with its classic design and traditional elements such as deep button tufting, scrolled arms, and nailhead accents. Featuring soft velvet upholstery, this chair stands as a streamlined statement piece that can change the whole flow of your living room, creating an open, clean space. Finished with beautifully turned legs, this chair provides an elegant touch to any room.','/assets/img/Chairs/Thelma+Velvet+Chesterfield+Chair.jpg',325.99);  

INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Ahart Frame Coffee Table','Your coffee table is a style centerpiece for your living ensemble, and whether you are gathering a room style or gathering all of your friends, a piece like this is perfect for lending your ensemble a modern accent. Crafted from a black-finished iron-based with a diamond-patterned base and capped with a mango wood surface, this table is brimming with on-trend mixed-material appeal.','/assets/img/Ahart+Frame+Coffee+Table.jpg',529.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Cross Legs Coffee Table with Storage','The frame of this fashionable coffee table was crafted using a smooth, consistent MDF wood and its table top was constructed using glass creating timeless fashion and adding to the appealing style of this piece.','/assets/img/Cross+Legs+Coffee+Table+with+Storage.jpg',469.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Denning Coffee Table','Is the seating ensemble feeling empty? Try a coffee table! Not only do they anchor your space, but they offer room to stage a display and serve up trays of treats when you find yourself entertaining. This one, for example, is simple and stylish. Its wood frame is classic, pairing clean lines with a neutral solid finish for versatility. The shelf below includes two baskets, perfect for storing everything from blankets to DVDs.','/assets/img/Denning+Coffee+Table.jpg',224.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Devito Cross Legs Coffee Table with Storage','Whether the surface for a game night or just the perfect perch for keeping cups in easy reach, this coffee table is an essential place to gather in your living room ensemble. Crafted from metal, it features an X-shaped base with clean lines for a touch of contemporary appeal, while neutral hues allow it to blend with your colour scheme. The manufactured wood top showcases a rectangular silhouette and can support up to 125 pounds after assembly.','/assets/img/Devito+Cross+Legs+Coffee+Table+with+Storage.jpg',159.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Dorsey End Table','Bring a clean-lined contemporary style to your seating ensemble with this side table! Crafted from manufactured wood, the streamlined square tabletop showcases a faux marble design with laminate, providing a perfect platform for everything from drinks and appetizers to remotes and coasters while staying sure to grab glances. Rounding out the design, the metal sled-style base features four straight legs and a square base. Best of all, its neutral hues allow this piece to blend with a variety of colour schemes.','/assets/img/Tables/Dorsey+End+Table.jpg',91.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Elizabeth End Table','Mid-century modern is having a moment, and one look at the sinuous edges of this end table will tell you why. This design, crafted from walnut, stands atop three slightly splayed legs, showcasing a rounded triangular top characteristic of mid-century aesthetics. It is wood grain details bring a dash of rustic appeal to the living room next to the sofa or the bedside – this handy table is so versatile, after all!','/assets/img/Tables/Elizabeth+End+Table.jpg',91.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Emington End Table With Storage','When beautifying your bedroom, emboldened elegance starts right at your side - your bedside, that is! Build a distinctive display from the ground up with this elegant table with storage, offering traditional charm with a splash of unexpected style. Crafted of solid and composite wood, it is founded atop four concave legs with a versatile solid finish that beautifully blends. Make it shine by adding on a glossy glowing lamp, lovely in a neutral hue or adding a little more eye-catching appeal in a brilliant blue or ravishing red. For a finishing touch with a touch of personal style, try adding in a few framed family photos or a vase of freshly-picked flowers from your garden. Need a little extra storage space? No problem! Just use this pleasant pieces single drawer or open lower shelf to keep nighttime essentials effortlessly on hand.','/assets/img/Tables/Emington+End+Table+With+Storage.jpg',106.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Haines Tray Top End Table with Storage','Perfectly sandwiched between living room furniture or filling empty wall space, this clean-lined end table is purpose-made for cutting clutter and brings transitional style to your home. Its unique flip-top design conceals interior storage space ideal for TV remotes and playing cards, while a lower shelf offers additional storage and display space.','/assets/img/Tables/Haines+Tray+Top+End+Table+with+Storage.jpg',141.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Harlan End Table','If you need a versatile and high functioning furniture piece, look no further than this contemporary style accent table. The spacious rectangular tabletop made from quality MDF material has a chic laminated surface supported by sturdy metal legs that showcase intersecting circles in a stylish design. Slip the sturdy chrome metal base under a sofa or armchair and use it to put down your drinks and snacks or as a convenient place for your tablet or laptop within reach. You can also set it on the side as a handy end table next to a sofa, armchair, or a bed. Easy to move from room to room, you will end up buying more than one!','/assets/img/Tables/Harlan+End+Table.jpg',102.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Maeve Round End Table','On-trend style and essential function combine to create this end table, a perfect fit for mid-century and contemporary spaces. Its circular base, crafted from steel in a metallic finish, features an openwork silhouette that supports a coordinating wood top with a marble-inspired hue. It measures 24'' H x 16'' W x 16'' D overall and can be pulled closer to the sofa than your average end table thanks to its open design.','/assets/img/Tables/Maeve+Round+End+Table.jpg',102.999);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Maquoit End Table With Storage','Pairing a clean-lined manufactured wood design, lower display shelf, and single drawer, this understated side table is the perfect pairing of simple utility and subtle style. Set it in the living room next to a striped arm chair to curate a cozy reading nook in your space, then stack hardcover novels topped with a rope-wrapped candle hurricane on the lower shelf to tie the ensemble together. Updating the master suite? Let a pair of these end tables serve as simple nightstands beside your headboard, then top them off with matching ceramic table lamps to cast a warm glow over the environment.','/assets/img/Tables/Maquoit+End+Table+With+Storage.jpg',102.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Sizemore End Table with Storage','This Sizemore End Table will be your favourite accent piece with its top form and stylized legs. One is sure to fit perfectly with your style.','/assets/img/Tables/Sizemore+End+Table+with+Storage.jpg',139.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Stoneford End Table','An essential in any living room arrangement, end tables act as a perch for lamps, books, and other decorative accents. This design also sets the tone for a traditional space, displaying a clean-lined silhouette and x-shaped side braces for a touch of visual intrigue and increased stability. Crafted from manufactured wood, its two open shelves offer space aplenty for anything you want to keep close at hand in the den.','/assets/img/Tables/Stoneford+End+Table.jpg',127.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Tiara End Table','Whether you are putting little trinkets on display or accenting your well-curated living room or den seating group, this understated and stylish end table is sure to tie any look together. Made from metal and coated in a gold finish, this end table bring a bit of luxe appeal to any aesthetic, while straight-lined legs and a tray-style top tie the table together in contemporary style. The table top is also removable, making it perfect as an impromptu cocktail tray.','/assets/img/Tables/Tiara+End+Table.jpg',589.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Wasser End Table','Every sofa’s sidekick, end tables display decor, hold TV remotes and beverages, and round out seating ensembles in style. Take this one for example: Crafted from metal, the base boasts a gold finish for a glint of glamour in your living room look. Up top, the circular tabletop is made from manufactured wood and sports a solid neutral colour for a look that won’t easily clash with your current colour palette.','/assets/img/Tables/Wasser+End+Table.jpg',86.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Grundy Lift Top Coffee Table','Second, only to the sofa, coffee tables are living room icons. They’re ubiquitous in all interior designs and come in a seemingly endless amount of styles. What’s your favourite? For fans of eclectic, boho-inspired accents, this coffee table is a perfect pick. It’s built from manufactured wood with turned feet, blocky corner supports. The graphic side panels feature colourful tile patterns that will instantly add a pop of bright colour which will stand out in your home décor. What’s more, half of the top lifts up, bringing drinks and laptops close as it reveals storage space for spare blankets, books, and beyond.','/assets/img/Grundy+Lift+Top+Coffee+Table.jpg',429.99);

INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (4,'Amia 2 Piece Living Room Set','Anchor your living room in contemporary style with this two-piece living room set, including one sofa and one loveseat. Founded on solid and manufactured wood frames, each sofa features a full back, track arms, and tapered block legs in a dark finish. Enveloped in polyester upholstery, each sofa features biscuit tufting and detail stitching for a tailored touch, while thick foam seat and back cushions provide comfort and support. Patterned throw pillows complete the set.','/assets/img/Amia+2+Piece+Living+Room+Set.jpg',1189.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (4,'Arminta Chesterfield 2 Piece Living Room Set','A true style sophisticate, the Chesterfield sofa has made its appearance in upscale glam-inspired ensembles, Victorian homes, and more for centuries. Today, they fit just as well into wood-panelled libraries as they do in downtown studio apartments. Take this one for example: Crafted from a solid wood frame with Wood legs, it showcases a pleated design on its foam-filled velvet upholstery. Plus, it arrives with two bolster pillows for a stylish added accent.','/assets/img/Arminta+Chesterfield+2+Piece+Living+Room+Set.jpg',1689.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (4,'Beverly Configurable Living Room Set','Apartment Size Set and Removable Cushions','/assets/img/Beverly+Configurable+Living+Room+Set.jpg',2649.97);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (4,'Brockway 4 Piece Living Room Set','This Brockway 4 Piece Living Room Set comes with chic style, classic fabrics, and undeniable style. This set will make your home the most elegant in the neighbourhood. A round cocktail ottoman and accent chair in fabrics that complement the sofa.','/assets/img/Brockway+4+Piece+Living+Room+Set.jpg',4599.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (4,'Configurable Living Room Set','Our fabric, sourced from around the world, selected for its quality, style and value and stored in our climate controlled fabric warehouse, is then cut, sewn and applied to create your finished piece of upholstered furniture.','/assets/img/Configurable+Living+Room+Set.jpg',2669.97);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (4,'Espen Configurable Living Room Set','Apartment Size Set','/assets/img/Espen+Configurable+Living+Room+Set.jpg',1379.98);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (4,'Mable Configurable Living Room Set','As comfortable as it is visually striking, this collection will add fresh design to your home. Upholstered in plush, durable velvet it features channel tufting and brushed gold steel legs. This collection is ready to revamp your space.','/assets/img/Mable+Configurable+Living+Room+Set.jpg',1629.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (4,'Mauk Configurable Living Room Set','Our fabric, sourced from around the world, selected for its quality, style and value and stored in our climate controlled fabric warehouse, is then cut, sewn and applied to create your finished piece of upholstered furniture.','/assets/img/Mauk+Configurable+Living+Room+Set.jpg',1579.98);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (4,'Paes 3 Piece Living Room Set','This 3 Piece Living Room Set is produced utilizing solid hardwoods and has sinuous spring cushioning along with high-density padding for that bounce back feel every time you sit. Sink into this sofa-chaise with matching loveseat and ottoman set to enjoy a relaxing and attractive setting in your home.','/assets/img/Paes+3+Piece+Living+Room+Set.jpg',3499.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (4,'Persaud Classic Chesterfield 2 Piece Living Room Set','The perfect piece to reflect your regal tastes, this classic living room set anchors your seating ensemble in timeless appeal. Crafted from wood, this dapper design strikes an updated, clean-lined silhouette with tight square arms and wood tapered feet. Crushed velvet upholstery brings out this sofa’s glamorous side, while exquisite details including high-density foam fill with spring support, piped seat cushions, matching bolster pillows, and a button-tufted backrest elevates the design.','/assets/img/Persaud+Classic+Chesterfield+2+Piece+Living+Room+Set.jpg',1499.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (4,'Prospect 2 Piece Upholstered Fabric Loveseat and Armchair Set in Light Grey','Craft a contemporary and stylish lounge with this living room set! It arrives with a loveseat and armchair, perfect for accenting your existing assembly, filling out a sitting room, or making a lounge space in your small apartment. Each piece is upholstered in 100% polyester in a solid hue and showcases button tufting for a fun accent. This set espresso-stained wooden legs include non-marking foot caps to help protect your floors.','/assets/img/Prospect+2+Piece+Upholstered+Fabric+Loveseat+and+Armchair+Set+in+Light+Grey.jpg',929.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (4,'Rosalie Configurable Living Room Set','Apartment Size Set and Removable Cushions','/assets/img/Rosalie+Configurable+Living+Room+Set.jpg',4239.96);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (4,'Saginaw 3 Piece Living Room Set','Anchor your living room in Scandinavian-inspired style with this three-piece set, complete with one sofa and two matching armchairs. Crafted with solid rubberwood frames, these pieces are built with coil spring seats, filled with foam, and upholstered with a polyester blend fabric. Their slightly flared arms and cherry-finished splayed legs contribute to their mid-century modern look, while a single row of tufted details along their tight backs lends these streamlined seats a touch of texture. Some assembly is required upon arrival.','/assets/img/Saginaw+3+Piece+Living+Room+Set.jpg',3239.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (4,'Serta Upholstery Hamza Configurable Living Room Set','This Configurable Living Room Set begins with milling and drying their own hardwoods at their lumberyard facility to ensure that their frames are built to last without warping, twisting, or cracking. From there, the lumber travels to one of their frame shops where the wood is cut, shaped, and assembled into the highest quality frames. The foam and fibre parts, built with eco-friendly practises and recycled materials are cut to size at one of two nearby foam processing plants. These components are then joined in one manufacturing centre where they are assembled into your piece of furniture. Their fabric, sourced from around the world, selected for its quality, style, and value and stored in their climate controlled fabric warehouse, is then cut, sewn and applied to create your finished piece of upholstered furniture.','/assets/img/Serta+Upholstery+Hamza+Configurable+Living+Room+Set.jpg',1859.98);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (4,'Sumner 2 Piece Living Room Set','Beautifully styled brimming with modern appeal, this classic set boasts a timeless yet minimalist aesthetic making it the perfect piece for your living room or seating area. A tailored design, the classically styled frame gives this piece a timeless appearance that is at home in both formal and casual settings. A subtly tufted back add elegant detail to this mid-century modern inspired set, bringing attention to angular track arms and solid wood legs with a brown finish. The soft two-tone matte velvet upholstery adds to its classic appeal and highlights its sculptural silhouette. This set is a unique piece that will complement the decor of any living room or den in your home.','/assets/img/Sumner+2+Piece+Living+Room+Set.jpg',1489.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (4,'Surakarta Configurable Living Room Set','Upholstery Material: Faux leather','/assets/img/Surakarta+Configurable+Living+Room+Set.jpg',4419.97);

INSERT INTO users (userid, userpassword, userfname, userlname, userrole, useremail, userphone, useraddress) VALUES ('sahar', '$2a$10$wjLrbcYC1VBRn5eAcsvyvedY7dWy4HTYneccT36LT7FqvH3FkoWua', 'Sahar', 'Sagharichi', 'buyer', 'sahar@gmail.com', '6477777777', '9088 Younge St.');
INSERT INTO users (userid, userpassword, userfname, userlname, userrole, useremail, userphone, useraddress) VALUES ('majid', '$2a$10$wjLrbcYC1VBRn5eAcsvyvedY7dWy4HTYneccT36LT7FqvH3FkoWua', 'Majid', 'Paktinat' , 'seller', 'majid@gmail.com', '5144444444', '9090 Yonge St.');




