USE onlinestore_db;

INSERT INTO categories (categoryname) VALUES ('Sofas');
INSERT INTO categories (categoryname) VALUES ('Chairs');
INSERT INTO categories (categoryname) VALUES ('Tables');

INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Flared ArmLoveseat','Rainy weekend afternoons are meant for naps, and some of the best naps happen on a couch in front of the TV, fireplace, or even a window with a view of the rain. This loveseat, for example, has a frame constructed of solid and manufactured wood, upholstered with 100% polyester, and filled with foam. It features flared arms, a tufted back, and nailhead trim. Needing light assembly, you will be lounging on this sectional in no time.','./public/assets/img/61.75%22+Flared+Arm+Loveseat.jpg',609.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Bel Air Sofa','Anchor your living room in sophisticated style and impeccable comfort with a single addition. Perfectly balancing wood accents with fabric upholstery, this impressive sofa offers your home a charming mid-century modern upgrade. This piece offers a beautiful button tufted design that is finished with diamond stitching in the backrest and waffle stitching in the seating. Completed with iconic splayed legs with gold tips and lovely rolled accent pillows, this refined sofa will make any interior space into a stunning masterpiece.','./public/assets/img/Bel-Air+Sofa.jpg',589.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Benitez Full 76" Convertible Sofa','With its streamlined silhouette and simple, squared cushions, this mid-century modern-inspired sofa lends inviting appeal to your seating ensemble. Featuring a frame made from a practical mixture of solid and manufactured wood in a rich brown finish, this design sports button-tufted faux leather upholstery, innerspring coil support, slick track arms, and five round tapered legs. When you’re finished watching your favourite shows and it’s time to retire, just fold the back down and this charismatic design effortlessly converts into a bed that sleeps two.','./public/assets/img/Benitez+Full+76%22+Convertible+Sofa.jpg',509.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Bjorn 59" Rolled Arm Settee','This settee is the perfect pick for a small-scale seating ensemble or a bedroom accent. Made from solid maple wood, it offers a traditional appearance with rolled arms and turned legs finished in walnut. Foam padding and web suspension add comfort to the seat, while 100% polyester upholstery ties it all together with button tufts and a neutral solid hue.','./public/assets/img/Bjorn+59%22+Rolled+Arm+Settee.jpg',479.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Corwin Convertible Sleeper','The Corwin pairs classic and modern in streamlined style. Featuring high density foam and sleek chrome metal legs and self-pipping tufting, this sofa effortlessly converts quickly to a bed. Surprise your guests and re-define comfort with the Corwin.','./public/assets/img/Corwin+Convertible+Sleeper.jpg',249.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Darren Tufted Loveseat','Perfect for rounding out a seating ensemble or a space-conscious area a lounge-worthy touch, loveseats like this are a great option for all the comfort of a sofa without dominating your home square footage. Crafted from a solid wood frame wrapped in 100% linen, this piece features a clean-lined silhouette perfect for a contemporary look. Tapered wood legs with a dark espresso finish and button tufting round this piece out with a touch of mid-century style.','./public/assets/img/Darren+Tufted+Loveseat.jpg',499.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Koger Velvet 88" Flared Arm Sofa','Lean back and lounge in luxurious style on this stunning sofa. This sofa features plush velvet upholstery that is both classy and sumptuous against your skin, a single seat cushion and rounded arms that curve into a low, rounded back, creating a perfect, modern piece for your home. Gold stainless steel legs support this sofa and provide a stunning contrast to the sofa plush.','./public/assets/img/Koger+Velvet+88%22+Flared+Arm+Sofa.jpg',1,369.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Marcelo 40.5" Armless Settee','A spacious work space chair, a seat at the foot of the bed; you name it, this settee brings style and function to any room of the house. Upholstered in 100% polyester, this piece sports a bold damask pattern for a touch of bohemian appeal, while solid wood legs, awash in dark espresso, complete the look. Sporting a clean, arm less silhouette, this settee pulls up flush to tables and coordinates effortlessly with existing furniture – seating two and holding up to 500 lbs. wherever it lives.','./public/assets/img/Marcelo+40.5%22+Armless+Settee.jpg',263.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Minter 89" Pillow Top Arm Sofa Bed','This transitional sleeper sofa features very plush pillow top arms for additional comfort while sitting, reclining or sleeping. A single touch transforms this full-size sleeper sofa into a bed. Make room for an unexpected guest or create a modern bedroom with this updated convertible futon that is so easy to assemble. The sofa sleeper is a very versatile piece of furniture that has a three-position click style hinge which allows you to sit, recline or sleep 2 comfortably. Polyester fibre, foam and innerspring seat and back cushion. No annoying bar in the back for added sleeping comfort.','./public/assets/img/Minter+89%22+Pillow+Top+Arm+Sofa+Bed.jpg',599.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Pepperell 72" Square Arm Sofa Bed','Going from day to night in a snap, this sleeper sofa is a perfect pick for any space. Crafted from solid and manufactured wood, this streamlined design is wrapped in linen upholstery for a touch of texture, while button tufts give it a dash of classic character. Got an unexpected guest? Simply transform this item into a sleeper, and voila – a space for them to rest their head. It measures 34'' H x 81'' W x 39'' D overall.','./public/assets/img/Pepperell+72%22+Square+Arm+Sofa+Bed.jpg',669.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Quinones Chesterfield 54 inches Rolled Arms Loveseat','Modelled after the classic British Chesterfield sofa, this loveseat brings a traditional element to your den, library, or home office. Upholstered with inviting fabric and filled with foam, its tight back and rolled arms feature deep button tufting as a nod to the iconic piece of furniture. It sits atop four stacked bun feet – simply screw them in for easy assembly, then curl up with a good book or cup of tea!','./public/assets/img/Quinones+Chesterfield+54+inches+Rolled+Arms+Loveseat.jpg',739.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (1,'Stevie Tufted Back Convertible Sofa','The Novogratz Stevie Futon is the perfect modern sofa bed for those who want practicality without compromising on style. Designed with rounded edges on the armrests, back and seat, the Stevie also features some button tufted detailing in the soft velvet upholstery. This convertible sofa bed is constructed with a strong plywood frame to ensure that it will last you through university and make it into your first apartment. To make this futon even better, the Novogratz Stevie Futon is built with a multi-functional design that allows you to recline the backrest between three position with an easy push or pull. This means you get to choose if you want your futon to be in a sitting position for long hours of studying, in a lounging position for a weekend long movie marathon, or in a sleeping position for hosting your friends overnight during the weekend. Available in multiple trendy colours, the Novogratz Stevie Futon is the ideal option to add a pop of style to your living room, home office or guest bedroom.','./public/assets/img/Stevie+Tufted+Back+Convertible+Sofa.jpg',469.99);

INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Brittnie Barrel Chair','This chair combines the traditional and classic style, which are perfect for your restaurant, living room, coffee house, patio, bedroom, or any other decor theme, an ergonomic oversized chair, designed for comfort, durability, and impeccable style.','./public/assets/img/Brittnie+Barrel+Chair.jpg',249.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Bulter Armchair','This Armchair showcases a scrolling botanical motif for a pop of pattern. This low-profile piece is crafted with a solid birch frame, foam fill, and quality upholstery to offer a firm feel as you sit back and relax.','./public/assets/img/Bulter+Armchair.jpg',206.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Didonato Velvet Tufted Upholstered Armchair','This elegant accent chair updates the classic armchair with dramatic curves and embracing comfort. With lustrous highlights and shadows, the velvet upholstery and tufted button.','./public/assets/img/Didonato+Velvet+Tufted+Upholstered+Armchair.jpg',409.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Garren 22.4" Club Chair','Showcasing simplified design and a clean-cut silhouette, this charismatic armchair is a mid-century modern style statement piece perfect for your living room or study. Made with a kiln-dried solid hardwood frame, this dapper design sports plush polyester blend upholstery with high-density foam fill and pocket coil suspension, sleek track arms, two bolster pillow cushions, and round, tapered, rubberwood legs.','./public/assets/img/Garren+22.4%22+Club+Chair.jpg',329.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Halesworth Armchair','A flared, button tufted back and loose seat nestled in this classic frame make this chair a charming addition to your living space. Wrapped roll arms and box seat piping back make the styling complete; every detail thought of','./public/assets/img/Halesworth+Armchair.jpg',299.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Holeman Velvet Slipper Chair','Fun and funky, this chair will add a vibrant accent to your home’s modern décor. This retro-inspired accent chair is sure to draw attention. Dark brown finished wood legs, button accent, and contoured shape lend to the unique styling of the chair.','./public/assets/img/Holeman+Velvet+Slipper+Chair.jpg',179.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Jayde Armchair','Rounding out your decor while providing sensible seating arrangements in small spaces, side chairs offer style and versatility to any interior design. Take this one for example: crafted from solid wood, it features four legs (two turned and two flared) awash in a neutral espresso finish, while the seat and barrel back boast foam-filled linen upholstery in a solid hue. Plus, it sports a button-tufted accents and nailhead trim for eye-catching appeal.','./public/assets/img/Jayde+Armchair.jpg',409.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Kayla Lounge Chair','Whether pulled up to your dining room ensemble or accenting your bedroom or living room look, this side chair brings contemporary style with a touch of rustic appeal to any space. Crafted from solid wood, the frame features two curved arms and boasts a natural wood grain brown finish for a dash of classic character. Plus, it showcases 100% polyester upholstery filled with foam for added comfort.','./public/assets/img/Kayla+Lounge+Chair.jpg',329.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Nisha 23" Wingback Arm Chair','A classic silhouette gets a contemporary upgrade in this curated chair. Founded on a solid birch wood frame, this dapper design strikes an updated wingback silhouette with curvy track arms and tapered square legs in a deep espresso finish. Sporting a fashionable solid hue, brushed polyester upholstery envelops the whole chair, accented by corded edges for a tailored touch, while web suspension, pocket springs support, and synthetic fibre-wrapped foam cushion cores provide comfort and support.','./public/assets/img/Nisha+23%22+Wingback+Arm+Chair.jpg',409.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (2,'Rotterdam 22.5" Armchair','Accent a traditional dining room set or provide extra seating in the living room with this armchair. Crafted from a solid and manufactured wood frame, it showcases arms that start with a curve and end in a square shape, and a straight back for an updated yet traditional design. Upholstered in a polyester blend, its seat and back feature a foam fill for an inviting look. Nailhead trim completes the look.','./public/assets/img/Rotterdam+22.5%22+Armchair.jpg',405.99);

INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Dorsey End Table','Bring a clean-lined contemporary style to your seating ensemble with this side table! Crafted from manufactured wood, the streamlined square tabletop showcases a faux marble design with laminate, providing a perfect platform for everything from drinks and appetizers to remotes and coasters while staying sure to grab glances. Rounding out the design, the metal sled-style base features four straight legs and a square base. Best of all, its neutral hues allow this piece to blend with a variety of colour schemes.','./public/assets/img/Dorsey+End+Table.jpg',91.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Elizabeth End Table','Mid-century modern is having a moment, and one look at the sinuous edges of this end table will tell you why. This design, crafted from walnut, stands atop three slightly splayed legs, showcasing a rounded triangular top characteristic of mid-century aesthetics. It is wood grain details bring a dash of rustic appeal to the living room next to the sofa or the bedside – this handy table is so versatile, after all!','./public/assets/img/Elizabeth+End+Table.jpg',91.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Emington End Table With Storage','When beautifying your bedroom, emboldened elegance starts right at your side - your bedside, that is! Build a distinctive display from the ground up with this elegant table with storage, offering traditional charm with a splash of unexpected style. Crafted of solid and composite wood, it is founded atop four concave legs with a versatile solid finish that beautifully blends. Make it shine by adding on a glossy glowing lamp, lovely in a neutral hue or adding a little more eye-catching appeal in a brilliant blue or ravishing red. For a finishing touch with a touch of personal style, try adding in a few framed family photos or a vase of freshly-picked flowers from your garden. Need a little extra storage space? No problem! Just use this pleasant pieces single drawer or open lower shelf to keep nighttime essentials effortlessly on hand.','./public/assets/img/Emington+End+Table+With+Storage.jpg',106.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Haines Tray Top End Table with Storage','Perfectly sandwiched between living room furniture or filling empty wall space, this clean-lined end table is purpose-made for cutting clutter and brings transitional style to your home. Its unique flip-top design conceals interior storage space ideal for TV remotes and playing cards, while a lower shelf offers additional storage and display space.','./public/assets/img/Haines+Tray+Top+End+Table+with+Storage.jpg',141.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Harlan End Table','If you need a versatile and high functioning furniture piece, look no further than this contemporary style accent table. The spacious rectangular tabletop made from quality MDF material has a chic laminated surface supported by sturdy metal legs that showcase intersecting circles in a stylish design. Slip the sturdy chrome metal base under a sofa or armchair and use it to put down your drinks and snacks or as a convenient place for your tablet or laptop within reach. You can also set it on the side as a handy end table next to a sofa, armchair, or a bed. Easy to move from room to room, you will end up buying more than one!','./public/assets/img/Bel-Air+Sofa.jpg',102.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Maeve Round End Table','On-trend style and essential function combine to create this end table, a perfect fit for mid-century and contemporary spaces. Its circular base, crafted from steel in a metallic finish, features an openwork silhouette that supports a coordinating wood top with a marble-inspired hue. It measures 24'' H x 16'' W x 16'' D overall and can be pulled closer to the sofa than your average end table thanks to its open design.','./public/assets/img/Maeve+Round+End+Table.jpg',102.999);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Maquoit End Table With Storage','Pairing a clean-lined manufactured wood design, lower display shelf, and single drawer, this understated side table is the perfect pairing of simple utility and subtle style. Set it in the living room next to a striped arm chair to curate a cozy reading nook in your space, then stack hardcover novels topped with a rope-wrapped candle hurricane on the lower shelf to tie the ensemble together. Updating the master suite? Let a pair of these end tables serve as simple nightstands beside your headboard, then top them off with matching ceramic table lamps to cast a warm glow over the environment.','./public/assets/img/Maquoit+End+Table+With+Storage%A0.jpg',102.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Sizemore End Table with Storage','This Sizemore End Table will be your favourite accent piece with its top form and stylized legs. One is sure to fit perfectly with your style.','./public/assets/img/Sizemore+End+Table+with+Storage.jpg',139.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Stoneford End Table','An essential in any living room arrangement, end tables act as a perch for lamps, books, and other decorative accents. This design also sets the tone for a traditional space, displaying a clean-lined silhouette and x-shaped side braces for a touch of visual intrigue and increased stability. Crafted from manufactured wood, its two open shelves offer space aplenty for anything you want to keep close at hand in the den.','./public/assets/img/Stoneford+End+Table.jpg',127.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Tiara End Table','Whether you are putting little trinkets on display or accenting your well-curated living room or den seating group, this understated and stylish end table is sure to tie any look together. Made from metal and coated in a gold finish, this end table bring a bit of luxe appeal to any aesthetic, while straight-lined legs and a tray-style top tie the table together in contemporary style. The table top is also removable, making it perfect as an impromptu cocktail tray.','./public/assets/img/Tiara+End+Table.jpg',589.99);
INSERT INTO products (categoryid,productname,productdescription,productimage,productprice) VALUES (3,'Wasser End Table','Every sofa’s sidekick, end tables display decor, hold TV remotes and beverages, and round out seating ensembles in style. Take this one for example: Crafted from metal, the base boasts a gold finish for a glint of glamour in your living room look. Up top, the circular tabletop is made from manufactured wood and sports a solid neutral colour for a look that won’t easily clash with your current colour palette.','./public/assets/img/Wasser+End+Table.jpg',86.99);

INSERT INTO users (userid, userpassword, userfname, userlname, userrole, useremail, userphone, useraddress) VALUES ('sahar123', '123', 'Sahar', 'Sagharichi', 'buyer', 'sahar@gmail.com', '6477777777', '9088 Younge St.');
INSERT INTO users (userid, userpassword, userfname, userlname, userrole, useremail, userphone, useraddress) VALUES ('majid456', '456', 'Majid', 'Paktinat' , 'seller', 'majid@gmail.com', '5144444444', '9090 Yonge St.');




